-- begin CCT_COMPLAINT
alter table CCT_COMPLAINT add constraint FK_CCT_COMPLAINT_ASSIGNEE foreign key (ASSIGNEE_ID) references SEC_USER(ID)^
alter table CCT_COMPLAINT add constraint FK_CCT_COMPLAINT_CATEGORY foreign key (CATEGORY_ID) references CCT_COMPLAINT_CATEGORY(ID)^
alter table CCT_COMPLAINT add constraint FK_CCT_COMPLAINT_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID)^
create index IDX_CCT_COMPLAINT_CATEGORY on CCT_COMPLAINT (CATEGORY_ID)^
create index IDX_CCT_COMPLAINT_ASSIGNEE on CCT_COMPLAINT (ASSIGNEE_ID)^
create index IDX_CCT_COMPLAINT_IMAGE_FILE on CCT_COMPLAINT (IMAGE_FILE_ID)^
-- end CCT_COMPLAINT

-- begin CCT_ACTIVITY
alter table CCT_ACTIVITY add constraint FK_CCT_ACTIVITY_COMPLAINT foreign key (COMPLAINT_ID) references CCT_COMPLAINT(ID)^
create index IDX_CCT_ACTIVITY_COMPLAINT on CCT_ACTIVITY (COMPLAINT_ID)^
-- end CCT_ACTIVITY
